# .github/workflows/test.yml
name: Run Tests

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        SELLER_ID: ${{ secrets.SELLER_ID }}
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python -m unittest tests/re_test.py

    - name: Install build tools
      run: |
        python -m pip install build

    - name: Build package
      run: python -m build

    - name: Verify Build Output
      run: |
        if [ -z "$(ls dist/*.whl 2>/dev/null)" ]; then
          echo "Build failed: No .whl file found in dist directory."
          exit 1
        else
          echo "Build successful: .whl file found."
        fi
